export const weapons = [
  {
    name: "Small Battleax",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "37",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "1",
      w_type: "Axe",
      w_level: "1",
      w_pang: "14",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "2",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Battleaxe",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "2",
      w_type: "Axe2H",
      w_level: "1",
      w_pang: "27",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "5",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Small Wooden Bow",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "2",
      w_type: "Bow",
      w_level: "1",
      w_pang: "31",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "5",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Light Crossbow",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "2",
      w_type: "Crossbow",
      w_level: "1",
      w_pang: "29",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-15",
      w_agi: "2",
      w_amb: "",
      w_dex: "2",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Shark Tooth Dagger",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "37",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "1",
      w_type: "Dagger",
      w_level: "1",
      w_pang: "8",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-5",
      w_agi: "2",
      w_amb: "2",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Little Beat",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "37",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "1",
      w_type: "Mace",
      w_level: "1",
      w_pang: "12",
      w_mang: "6",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "2",
      w_str: "2",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "2",
      w_type: "Mace2H",
      w_level: "1",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Wooden Shield",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "37",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "1",
      w_type: "Shield",
      w_level: "1",
      w_pang: "",
      w_mang: "",
      w_pdeff: "9",
      w_crit: "0.02",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "5",
      w_wis: "",
    },
  },
  {
    name: "Iron Sword",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "37",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "1",
      w_type: "Sword",
      w_level: "1",
      w_pang: "12",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "2",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "2",
      w_type: "Sword2H",
      w_level: "1",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Staff of the Brightness",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "1",
      w_pang: "",
      w_mang: "28",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "5",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Simple Wand",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "1",
      w_pang: "",
      w_mang: "28",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "3",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "2",
    },
  },
  {
    name: "Staff of Obsession",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "1",
      w_pang: "",
      w_mang: "28",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "5",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Thunder Axe",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "1",
      w_type: "Axe",
      w_level: "20",
      w_pang: "31",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "5",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Great Battleaxe",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "2",
      w_type: "Axe2H",
      w_level: "20",
      w_pang: "64",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "10",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Nobler Wooden Bow",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "2",
      w_type: "Bow",
      w_level: "20",
      w_pang: "68",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "10",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Heaviness Crossbow",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "2",
      w_type: "Crossbow",
      w_level: "20",
      w_pang: "65",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-15",
      w_agi: "5",
      w_amb: "",
      w_dex: "5",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Balanced Dagger",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "1",
      w_type: "Dagger",
      w_level: "20",
      w_pang: "23",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-5",
      w_agi: "5",
      w_amb: "5",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "1",
      w_type: "Mace",
      w_level: "20",
      w_pang: "28",
      w_mang: "14",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "5",
      w_str: "5",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "2",
      w_type: "Mace2H",
      w_level: "20",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Iron Shield",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "1",
      w_type: "Shield",
      w_level: "20",
      w_pang: "",
      w_mang: "",
      w_pdeff: "17",
      w_crit: "0.04",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "10",
      w_wis: "",
    },
  },
  {
    name: "Blade of Doom",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "1",
      w_type: "Sword",
      w_level: "20",
      w_pang: "27",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "5",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "2",
      w_type: "Sword2H",
      w_level: "20",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Radiant Staff",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "20",
      w_pang: "",
      w_mang: "45",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "10",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Wand of Knowledge",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "20",
      w_pang: "",
      w_mang: "45",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "6",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "4",
    },
  },
  {
    name: "Staff of Devoured Souls",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "20",
      w_pang: "",
      w_mang: "45",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "10",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Jagged Broadaxe",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "1",
      w_type: "Axe",
      w_level: "40",
      w_pang: "64",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "10",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "War Axe",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "2",
      w_type: "Axe2H",
      w_level: "40",
      w_pang: "131",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "15",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Balanced Crossbow",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "2",
      w_type: "Bow",
      w_level: "40",
      w_pang: "133",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "15",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Crossbow of target Shot",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "2",
      w_type: "Crossbow",
      w_level: "40",
      w_pang: "131",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-15",
      w_agi: "7",
      w_amb: "",
      w_dex: "10",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Perfect Balanced Dagger",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "1",
      w_type: "Dagger",
      w_level: "40",
      w_pang: "49",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-5",
      w_agi: "10",
      w_amb: "10",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "1",
      w_type: "Mace",
      w_level: "40",
      w_pang: "59",
      w_mang: "30",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "7",
      w_str: "7",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "2",
      w_type: "Mace2H",
      w_level: "40",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Mighty Wall",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "1",
      w_type: "Shield",
      w_level: "40",
      w_pang: "",
      w_mang: "",
      w_pdeff: "31",
      w_crit: "0.06",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "15",
      w_wis: "",
    },
  },
  {
    name: "Oathkeeper Sword",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "1",
      w_type: "Sword",
      w_level: "40",
      w_pang: "57",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "10",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "2",
      w_type: "Sword2H",
      w_level: "40",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Staff of Holyness",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "40",
      w_pang: "",
      w_mang: "87",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "15",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Survivors Staff",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "40",
      w_pang: "",
      w_mang: "87",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "9",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "6",
    },
  },
  {
    name: "Staff of Abyss",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "40",
      w_pang: "",
      w_mang: "87",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "15",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Gale of Axe",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "1",
      w_type: "Axe",
      w_level: "60",
      w_pang: "89",
      w_mang: "",
      w_pdeff: "",
      w_crit: "0.05",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "15",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Big Crusher",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "2",
      w_type: "Axe2H",
      w_level: "60",
      w_pang: "182",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "20",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Valkyrie Tendon",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "2",
      w_type: "Bow",
      w_level: "60",
      w_pang: "195",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "20",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "The Huntress of the Shaddow",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "2",
      w_type: "Crossbow",
      w_level: "60",
      w_pang: "186",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "10",
      w_amb: "",
      w_dex: "14",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Lightbreaker",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "1",
      w_type: "Dagger",
      w_level: "60",
      w_pang: "77",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "15",
      w_amb: "15",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "1",
      w_type: "Mace",
      w_level: "60",
      w_pang: "82",
      w_mang: "41",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "9",
      w_str: "9",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "2",
      w_type: "Mace2H",
      w_level: "60",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Mighty Wall",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "1",
      w_type: "Shield",
      w_level: "60",
      w_pang: "",
      w_mang: "",
      w_pdeff: "78",
      w_crit: "0.08",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "20",
      w_wis: "",
    },
  },
  {
    name: "Dusk Blade",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "1",
      w_type: "Sword",
      w_level: "60",
      w_pang: "77",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "15",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "2",
      w_type: "Sword2H",
      w_level: "60",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Staff of Holyness",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "60",
      w_pang: "",
      w_mang: "156",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "25",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Wand of Rejuvenation",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "60",
      w_pang: "",
      w_mang: "156",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "15",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "10",
    },
  },
  {
    name: "Scepter of Lunar Eclipse",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "60",
      w_pang: "",
      w_mang: "156",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "25",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Dragons Breath",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "1",
      w_type: "Axe",
      w_level: "80",
      w_pang: "123",
      w_mang: "",
      w_pdeff: "",
      w_crit: "0.075",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "20",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Great Destroyer",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "2",
      w_type: "Axe2H",
      w_level: "80",
      w_pang: "233",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "30",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Bow of Dragon Roar",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "2",
      w_type: "Bow",
      w_level: "80",
      w_pang: "245",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "25",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Hunters Arbalist",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "2",
      w_type: "Crossbow",
      w_level: "80",
      w_pang: "241",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "15",
      w_amb: "",
      w_dex: "20",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Shaddowbreaker",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "1",
      w_type: "Dagger",
      w_level: "80",
      w_pang: "103",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "20",
      w_amb: "20",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "1",
      w_type: "Mace",
      w_level: "80",
      w_pang: "112",
      w_mang: "56",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "12",
      w_str: "12",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "2",
      w_type: "Mace2H",
      w_level: "80",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Shield of Divine Protection",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "1",
      w_type: "Shield",
      w_level: "80",
      w_pang: "",
      w_mang: "",
      w_pdeff: "144",
      w_crit: "0.1",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "25",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "1",
      w_type: "Sword",
      w_level: "80",
      w_pang: "111",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "20",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "2",
      w_type: "Sword2H",
      w_level: "80",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Glimmer of Hope",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "80",
      w_pang: "",
      w_mang: "293",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "30",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Wand of Oracle",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "80",
      w_pang: "",
      w_mang: "293",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "18",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "12",
    },
  },
  {
    name: "Soulstealer",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "80",
      w_pang: "",
      w_mang: "293",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "30",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Skybreaker",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "1",
      w_type: "Axe",
      w_level: "100",
      w_pang: "256",
      w_mang: "",
      w_pdeff: "",
      w_crit: "0.1",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "25",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Dimension",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "2",
      w_type: "Axe2H",
      w_level: "100",
      w_pang: "531",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "40",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Rayans Deracles",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "2",
      w_type: "Bow",
      w_level: "100",
      w_pang: "541",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "30",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Crossbow of the Shddowhunter",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "2",
      w_type: "Crossbow",
      w_level: "100",
      w_pang: "462",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-20",
      w_agi: "20",
      w_amb: "",
      w_dex: "25",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Blade of Damnation",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "1",
      w_type: "Dagger",
      w_level: "100",
      w_pang: "211",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-10",
      w_agi: "25",
      w_amb: "25",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "1",
      w_type: "Mace",
      w_level: "100",
      w_pang: "244",
      w_mang: "122",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "15",
      w_str: "15",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "2",
      w_type: "Mace2H",
      w_level: "100",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Himmelsbrecher",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "1",
      w_type: "Shield",
      w_level: "100",
      w_pang: "",
      w_mang: "",
      w_pdeff: "212",
      w_crit: "0.15",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "30",
      w_wis: "",
    },
  },
  {
    name: "Infernal Blade",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "1",
      w_type: "Sword",
      w_level: "100",
      w_pang: "232",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-15",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "25",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "2",
      w_type: "Sword2H",
      w_level: "100",
      w_pang: "",
      w_mang: "",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Rod of Divine Light",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "100",
      w_pang: "",
      w_mang: "498",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "40",
      w_int: "",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "",
    },
  },
  {
    name: "Rod of Ethernal Life",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "100",
      w_pang: "",
      w_mang: "498",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "25",
      w_str: "",
      w_vic: "",
      w_vita: "",
      w_wis: "15",
    },
  },
  {
    name: "Soul Eater",
    description: "",
    thumbnail: "",
    kind: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    weapon: {
      w_slots: "2",
      w_type: "Wand2H",
      w_level: "100",
      w_pang: "",
      w_mang: "498",
      w_pdeff: "",
      w_crit: "",
      w_block: "",
      w_speed: "-30",
      w_agi: "",
      w_amb: "",
      w_dex: "",
      w_faith: "",
      w_int: "",
      w_str: "",
      w_vic: "40",
      w_vita: "",
      w_wis: "",
    },
  },
];
