import { set } from "mongoose";

export const itemBackup = [
  {
    name: "Small Battleax",
    description: "",
    thumbnail: "",
    type: "Axe",
    category: "weapon",
    rang: 1,
    weight: 5,
    stacksize: 1,
    sellable: true,
    tradable: true,
    sell: 37,
    price: 0,
    rare: 3,
    attributes: {
      slots: 1,
      level: 1,
      maxlevel: 10,
      pang: 14,
      mang: 0,
      pdeff: 0,
      crit: 0,
      block: 0,
      speed: -10,
      health: 0,
      mana: 0,
      agility: 0,
      ambush: 0,
      dexerity: 0,
      faith: 0,
      int: 0,
      strength: 2,
      victim: 0,
      vita: 0,
      wisdom: 0,
      luck: 0,
      boni: {
        description: "",
        type: "",
        value: 0,
      },
      set: {
        amount: 0,
        description: "",
        type: "",
        value: 0,
      },
      effect: {
        description: "",
        type: "",
        chance: 0,
        value: 0,
        duration: 0,
      },
    },
      cd: 0,
      duration: 0,
      range: 0,
      isLegendary: false,
  },
  {
    name: "Battleaxe",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    slots: "2",
    type: "Axe2H",
    level: "1",
    pang: "27",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "5",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Small Wooden Bow",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    slots: "2",
    type: "Bow",
    level: "1",
    pang: "31",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "5",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Light Crossbow",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    slots: "2",
    type: "Crossbow",
    level: "1",
    pang: "29",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-15",
    health: "",
    mana: "",
    agility: "2",
    ambush: "",
    dexerity: "2",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Shark Tooth Dagger",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "37",
    price: "0",
    rang: "1",
    slots: "1",
    type: "Dagger",
    level: "1",
    pang: "8",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-5",
    health: "",
    mana: "",
    agility: "2",
    ambush: "2",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Little Mace",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "37",
    price: "0",
    rang: "1",
    slots: "1",
    type: "Mace",
    level: "1",
    pang: "12",
    mang: "6",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "2",
    strength: "2",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Big Mace",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    slots: "2",
    type: "Mace2H",
    level: "1",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Wooden Shield",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "37",
    price: "0",
    rang: "1",
    slots: "1",
    type: "Shield",
    level: "1",
    pang: "",
    mang: "",
    pdeff: "9",
    crit: "",
    block: "0.02",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "5",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Iron Sword",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "37",
    price: "0",
    rang: "1",
    slots: "1",
    type: "Sword",
    level: "1",
    pang: "12",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "2",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Longsword",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    slots: "2",
    type: "Sword2H",
    level: "1",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Staff of the Brightness",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    slots: "2",
    type: "Wand2H",
    level: "1",
    pang: "",
    mang: "28",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "5",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Simple Wand",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    slots: "2",
    type: "Wand2H",
    level: "1",
    pang: "",
    mang: "28",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "3",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "2",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Staff of Obsession",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "71",
    price: "0",
    rang: "1",
    slots: "2",
    type: "Wand2H",
    level: "1",
    pang: "",
    mang: "28",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "5",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Thunder Axe",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    slots: "1",
    type: "Axe",
    level: "20",
    pang: "31",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "5",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Great Battleaxe",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    slots: "2",
    type: "Axe2H",
    level: "20",
    pang: "64",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "10",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Nobler Wooden Bow",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    slots: "2",
    type: "Bow",
    level: "20",
    pang: "68",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "10",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Heaviness Crossbow",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    slots: "2",
    type: "Crossbow",
    level: "20",
    pang: "65",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-15",
    health: "",
    mana: "",
    agility: "5",
    ambush: "",
    dexerity: "5",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Balanced Dagger",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    slots: "1",
    type: "Dagger",
    level: "20",
    pang: "23",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-5",
    health: "",
    mana: "",
    agility: "5",
    ambush: "5",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Morningstar",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    slots: "1",
    type: "Mace",
    level: "20",
    pang: "28",
    mang: "14",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "5",
    strength: "5",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blazing Mace",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    slots: "2",
    type: "Mace2H",
    level: "20",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Iron Shield",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    slots: "1",
    type: "Shield",
    level: "20",
    pang: "",
    mang: "",
    pdeff: "17",
    crit: "",
    block: "0.04",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "10",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blade of Doom",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "94",
    price: "0",
    rang: "2",
    slots: "1",
    type: "Sword",
    level: "20",
    pang: "27",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "5",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Great Sword",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    slots: "2",
    type: "Sword2H",
    level: "20",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Radiant Staff",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    slots: "2",
    type: "Wand2H",
    level: "20",
    pang: "",
    mang: "45",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "10",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Wand of Knowledge",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    slots: "2",
    type: "Wand2H",
    level: "20",
    pang: "",
    mang: "45",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "6",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "4",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Staff of Devoured Souls",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "164",
    price: "0",
    rang: "2",
    slots: "2",
    type: "Wand2H",
    level: "20",
    pang: "",
    mang: "45",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "10",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Jagged Broadaxe",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    slots: "1",
    type: "Axe",
    level: "40",
    pang: "64",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "10",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "War Axe",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    slots: "2",
    type: "Axe2H",
    level: "40",
    pang: "131",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "15",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Balanced Crossbow",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    slots: "2",
    type: "Bow",
    level: "40",
    pang: "133",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "15",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Crossbow of target Shot",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    slots: "2",
    type: "Crossbow",
    level: "40",
    pang: "131",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-15",
    health: "",
    mana: "",
    agility: "7",
    ambush: "",
    dexerity: "10",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Perfect Balanced Dagger",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    slots: "1",
    type: "Dagger",
    level: "40",
    pang: "49",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-5",
    health: "",
    mana: "",
    agility: "10",
    ambush: "10",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "The Silencer",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    slots: "1",
    type: "Mace",
    level: "40",
    pang: "59",
    mang: "30",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "7",
    strength: "7",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Bessing of the Light Mace",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    slots: "2",
    type: "Mace2H",
    level: "40",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Mighty Wall",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    slots: "1",
    type: "Shield",
    level: "40",
    pang: "",
    mang: "",
    pdeff: "31",
    crit: "",
    block: "0.06",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "15",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Oathkeeper Sword",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "202",
    price: "0",
    rang: "3",
    slots: "1",
    type: "Sword",
    level: "40",
    pang: "57",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "10",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Sword of Victory",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    slots: "2",
    type: "Sword2H",
    level: "40",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Staff of Holyness",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    slots: "2",
    type: "Wand2H",
    level: "40",
    pang: "",
    mang: "87",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "15",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Survivors Staff",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    slots: "2",
    type: "Wand2H",
    level: "40",
    pang: "",
    mang: "87",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "9",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "6",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Staff of Abyss",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "357",
    price: "0",
    rang: "3",
    slots: "2",
    type: "Wand2H",
    level: "40",
    pang: "",
    mang: "87",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "15",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Gale of Axe",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    slots: "1",
    type: "Axe",
    level: "60",
    pang: "89",
    mang: "",
    pdeff: "",
    crit: "",
    block: "0.05",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "15",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Big Crusher",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    slots: "2",
    type: "Axe2H",
    level: "60",
    pang: "182",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "20",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Valkyrie Tendon",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    slots: "2",
    type: "Bow",
    level: "60",
    pang: "195",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "20",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "The Huntress of the Shaddow",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    slots: "2",
    type: "Crossbow",
    level: "60",
    pang: "186",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "10",
    ambush: "",
    dexerity: "14",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Lightbreaker",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    slots: "1",
    type: "Dagger",
    level: "60",
    pang: "77",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "15",
    ambush: "15",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Anguish of Peaceful Mind",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    slots: "1",
    type: "Mace",
    level: "60",
    pang: "82",
    mang: "41",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "9",
    strength: "9",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Meteroic Mace",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    slots: "2",
    type: "Mace2H",
    level: "60",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Antique shield",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    slots: "1",
    type: "Shield",
    level: "60",
    pang: "",
    mang: "",
    pdeff: "78",
    crit: "",
    block: "0.08",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "20",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Dusk Blade",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "453",
    price: "0",
    rang: "4",
    slots: "1",
    type: "Sword",
    level: "60",
    pang: "77",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "15",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Claymore",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    slots: "2",
    type: "Sword2H",
    level: "60",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Clearness of sins",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    slots: "2",
    type: "Wand2H",
    level: "60",
    pang: "",
    mang: "156",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "25",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Wand of Rejuvenation",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    slots: "2",
    type: "Wand2H",
    level: "60",
    pang: "",
    mang: "156",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "15",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "10",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Scepter of Lunar Eclipse",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "783",
    price: "0",
    rang: "4",
    slots: "2",
    type: "Wand2H",
    level: "60",
    pang: "",
    mang: "156",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "25",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Dragons Breath",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    slots: "1",
    type: "Axe",
    level: "80",
    pang: "123",
    mang: "",
    pdeff: "",
    crit: "",
    block: "0.075",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "20",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Great Destroyer",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    slots: "2",
    type: "Axe2H",
    level: "80",
    pang: "233",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "30",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Bow of Dragon Roar",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    slots: "2",
    type: "Bow",
    level: "80",
    pang: "245",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "25",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Hunters Arbalist",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    slots: "2",
    type: "Crossbow",
    level: "80",
    pang: "241",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "15",
    ambush: "",
    dexerity: "20",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Shaddowbreaker",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    slots: "1",
    type: "Dagger",
    level: "80",
    pang: "103",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "20",
    ambush: "20",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Mongingstar of the fallen Angel",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    slots: "1",
    type: "Mace",
    level: "80",
    pang: "112",
    mang: "56",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "12",
    strength: "12",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Rage of the Minotaur",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    slots: "2",
    type: "Mace2H",
    level: "80",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Shield of Divine Protection",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    slots: "1",
    type: "Shield",
    level: "80",
    pang: "",
    mang: "",
    pdeff: "144",
    crit: "",
    block: "0.1",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "25",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Redeem of Pain",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1081",
    price: "0",
    rang: "5",
    slots: "1",
    type: "Sword",
    level: "80",
    pang: "111",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "20",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Executioner Sword of Baldur",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    slots: "2",
    type: "Sword2H",
    level: "80",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Glimmer of Hope",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    slots: "2",
    type: "Wand2H",
    level: "80",
    pang: "",
    mang: "293",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "30",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Wand of Oracle",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    slots: "2",
    type: "Wand2H",
    level: "80",
    pang: "",
    mang: "293",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "18",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "12",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Soulstealer",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "1637",
    price: "0",
    rang: "5",
    slots: "2",
    type: "Wand2H",
    level: "80",
    pang: "",
    mang: "293",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "30",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Skybreaker",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    slots: "1",
    type: "Axe",
    level: "100",
    pang: "256",
    mang: "",
    pdeff: "",
    crit: "",
    block: "0.1",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "25",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Dimension",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    slots: "2",
    type: "Axe2H",
    level: "100",
    pang: "531",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "40",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Rayans Deracles",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    slots: "2",
    type: "Bow",
    level: "100",
    pang: "541",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "30",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Crossbow of the Shddowhunter",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    slots: "2",
    type: "Crossbow",
    level: "100",
    pang: "462",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-20",
    health: "",
    mana: "",
    agility: "20",
    ambush: "",
    dexerity: "25",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blade of Damnation",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    slots: "1",
    type: "Dagger",
    level: "100",
    pang: "211",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-10",
    health: "",
    mana: "",
    agility: "25",
    ambush: "25",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Guardien of the Light",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    slots: "1",
    type: "Mace",
    level: "100",
    pang: "244",
    mang: "122",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "15",
    strength: "15",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Hammer of Justice",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    slots: "2",
    type: "Mace2H",
    level: "100",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Skybreaker",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    slots: "1",
    type: "Shield",
    level: "100",
    pang: "",
    mang: "",
    pdeff: "212",
    crit: "",
    block: "0.15",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "30",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Infernal Blade",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "2273",
    price: "0",
    rang: "6",
    slots: "1",
    type: "Sword",
    level: "100",
    pang: "232",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-15",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "25",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Souls Torment Blade",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    slots: "2",
    type: "Sword2H",
    level: "100",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Rod of Divine Light",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    slots: "2",
    type: "Wand2H",
    level: "100",
    pang: "",
    mang: "498",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "40",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Rod of Ethernal Life",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    slots: "2",
    type: "Wand2H",
    level: "100",
    pang: "",
    mang: "498",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "25",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "15",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Soul Eater",
    description: "",
    thumbnail: "",
    category: "weapon",
    weight: "",
    rare: "3",
    stacksize: "1",
    sell: "3452",
    price: "0",
    rang: "6",
    slots: "2",
    type: "Wand2H",
    level: "100",
    pang: "",
    mang: "498",
    pdeff: "",
    crit: "",
    block: "",
    speed: "-30",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "40",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Granat",
    description: "Increases vitality by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "2",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Saphir",
    description: "Increases intelligence by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "2",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Amethyst",
    description: "Increases Wisdom by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "2",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Jade",
    description: "Increases Faith by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "2",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Achat",
    description: "Increases Luck by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "2",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Onyx",
    description: "Increases Victim by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "2",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Turmalin",
    description: "Increases Dexterity by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "2",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Opal",
    description: "Increases Dexterity by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "2",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Labradorit",
    description: "Increases Ambush by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "2",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Splinter Jaspis",
    description: "Increases Strength by +2.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "20",
    price: "",
    rang: "2",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "2",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Granat",
    description: "Increases vitality by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "4",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Saphir",
    description: "Increases intelligence by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "4",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Amethyst",
    description: "Increases Wisdom by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "4",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Jade",
    description: "Increases Faith by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "4",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Achat",
    description: "Increases Luck by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "4",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Onyx",
    description: "Increases Victim by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "4",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Turmalin",
    description: "Increases Dexterity by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "4",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Opal",
    description: "Increases Dexterity by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "4",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Labradorit",
    description: "Increases Ambush by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "4",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Fragment Jaspis",
    description: "Increases Strength by +4.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "50",
    price: "",
    rang: "3",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "4",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Granat",
    description: "Increases vitality by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "8",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Saphir",
    description: "Increases intelligence by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "8",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Amethyst",
    description: "Increases Wisdom by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "8",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Jade",
    description: "Increases Faith by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "8",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Achat",
    description: "Increases Luck by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "6",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Onyx",
    description: "Increases Victim by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "8",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Turmalin",
    description: "Increases Dexterity by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "8",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Opal",
    description: "Increases Dexterity by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "8",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Labradorit",
    description: "Increases Ambush by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "8",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Fragment Jaspis",
    description: "Increases Strength by +8.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "4",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "8",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Granat",
    description: "Increases vitality by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "10",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Saphir",
    description: "Increases intelligence by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "10",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Amethyst",
    description: "Increases Wisdom by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "10",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Jade",
    description: "Increases Faith by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "10",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Achat",
    description: "Increases Luck by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "8",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Onyx",
    description: "Increases Victim by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "10",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Turmalin",
    description: "Increases Dexterity by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "10",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Opal",
    description: "Increases Dexterity by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "10",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Labradorit",
    description: "Increases Ambush by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "10",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Ignoble Jaspis",
    description: "Increases Strength by +10.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "200",
    price: "",
    rang: "5",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "10",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Granat",
    description: "Increases vitality by +20.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "20",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Saphir",
    description: "Increases intelligence by +20.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "20",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Amethyst",
    description: "Increases Wisdom by +20.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "20",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Jade",
    description: "Increases Faith by +20.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "20",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Achat",
    description: "Increases Luck by +20.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "10",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Onyx",
    description: "Increases Victim by +20.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "20",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Turmalin",
    description: "Increases Dexterity by +20.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "20",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Opal",
    description: "Increases Dexterity by +20.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "20",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Labradorit",
    description: "Increases Ambush by +20.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "20",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Refined Jaspis",
    description: "Increases strength by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "500",
    price: "",
    rang: "6",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "20",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Granat",
    description: "Increases vitality by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "30",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Saphir",
    description: "Increases intelligence by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "30",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Amethyst",
    description: "Increases Wisdom by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "30",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Jade",
    description: "Increases Faith by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "30",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Achat",
    description: "Increases Luck by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "15",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Onyx",
    description: "Increases Victim by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "30",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Turmalin",
    description: "Increases Dexterity by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "30",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Opal",
    description: "Increases Dexterity by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "30",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Labradorit",
    description: "Increases Ambush by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "30",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Blessed Jaspis",
    description: "Increases strength by +30.",
    thumbnail: "",
    category: "upgrade",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "1000",
    price: "",
    rang: "7",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "30",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "",
    duration: "",
  },
  {
    name: "Granat",
    description:
      "The strong red color of the garnet symbolizes vitality and energy. Increases vitality by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "5",
    wisdom: "",
    luck: "",
    cd: "60",
    duration: "7200",
  },
  {
    name: "Saphir",
    description:
      "The deep, clear color of sapphire symbolizes intelligence and knowledge. Increases intelligence by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "5",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "60",
    duration: "7200",
  },
  {
    name: "Amethyst",
    description:
      "The violet color of amethyst stands for spiritual wisdom. Increases wisdom by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "5",
    luck: "",
    cd: "60",
    duration: "7200",
  },
  {
    name: "Jade",
    description:
      "The delicate green color of jade stands for good nature and harmony. Increases faith by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "5",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "60",
    duration: "7200",
  },
  {
    name: "Achat",
    description:
      "Agate stands for happiness and balance. Increases luck by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "60",
    duration: "7200",
  },
  {
    name: "Onyx",
    description:
      "The deep black color of onyx holds mysterious powers and has always been used to strengthen dark magic. Increases Victim by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "5",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "60",
    duration: "7200",
  },
  {
    name: "Turmalin",
    description:
      "The variety of colors in tourmaline stands for dexterity. Increases dexterity by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "5",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "60",
    duration: "7200",
  },
  {
    name: "Opal",
    description:
      "The shimmering play of colors in opal represents elegance and agility. Increases agility by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "5",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "60",
    duration: "7200",
  },
  {
    name: "Labradorit",
    description:
      "Labradorite stands for seeing through illusions. Increases ambush by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "5",
    dexerity: "",
    faith: "",
    int: "",
    strength: "",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "60",
    duration: "7200",
  },
  {
    name: "Jaspis",
    description:
      "Orange red jasper stands for strength, endurance and power. Increases strength by 5%.",
    thumbnail: "",
    category: "bufffood",
    weight: "5",
    rare: "",
    stacksize: "100",
    sell: "",
    price: "",
    rang: "",
    slots: "",
    type: "",
    level: "",
    pang: "",
    mang: "",
    pdeff: "",
    crit: "",
    block: "",
    speed: "",
    health: "",
    mana: "",
    agility: "",
    ambush: "",
    dexerity: "",
    faith: "",
    int: "",
    strength: "5",
    victim: "",
    vita: "",
    wisdom: "",
    luck: "",
    cd: "60",
    duration: "7200",
  }
  // {
  //   name: "",
  //   description: "",
  //   thumbnail: "",
  //   category: "",
  //   weight: "",
  //   rare: "",
  //   stacksize: "",
  //   sell: "",
  //   price: "",
  //   rang: "",
  //   slots: "",
  //   type: "",
  //   level: "",
  //   pang: "",
  //   mang: "",
  //   pdeff: "",
  //   crit: "",
  //   block: "",
  //   speed: "",
  //   health: "",
  //   mana: "",
  //   agility: "",
  //   ambush: "",
  //   dexerity: "",
  //   faith: "",
  //   int: "",
  //   strength: "",
  //   victim: "",
  //   vita: "",
  //   wisdom: "",
  //   luck: "",
  //   cd: "",
  //   duration: "",
  // },
];
