import mongoose, { set } from 'mongoose';

const itemSchema = mongoose.Schema({
    name: { type: String, required: true, unique: true },
    description: { type: String },
    thumbnail: { type: String },
    type: { type: String},
    category: { type: String},
    rang: { type: Number, default: 0 },
    weight: { type: Number, default: 1 },
    stacksize: { type: Number, default: 1 },
    sellable: { type: Boolean, default: true },
    tradable: { type: Boolean, default: true },
    sell: { type: Number, default: 0 },
    price: { type: Number, default: 0 },
    rare: { type: Number, default: 3 },
    attributes: {
      slots: { type: Number, default: 0 },
      level: { type: Number, default: 1 },
      maxLevel: { type: Number, default: 1 },
      upgrade: { type: Number, default: 1 },
      maxUpgrade: { type: Number, default: 1 },
      pang: { type: Number, default: 0 },
      mang: { type: Number, default: 0 },
      pdeff: { type: Number, default: 0 },
      crit: { type: Number, default: 0 },
      block: { type: Number, default: 0 },
      speed: { type: Number, default: 0 },
      health: { type: Number, default: 0 },
      mana: { type: Number, default: 0 },
      agility: { type: Number, default: 0 },
      ambush: { type: Number, default: 0 },
      dexerity: { type: Number, default: 0 },
      faith: { type: Number, default: 0 },
      int: { type: Number, default: 0 },
      strength: { type: Number, default: 0 },
      victim: { type: Number, default: 0 },
      vita: { type: Number, default: 0 },
      wisdom: { type: Number, default: 0 },
      luck: { type: Number, default: 0 },
      boni: {
        description: { type: String },
        type: { type: String },
        value: { type: Number, default: 0 },
      },
      set: {
        amount: { type: Number, default: 0 },
        description: { type: String },
        type: { type: String },
        value: { type: Number, default: 0 },
      },
      effect: {
        description: { type: String },
        type: { type: String },
        chance: { type: Number, default: 0 },
        value: { type: Number, default: 0 },
        duration: { type: Number, default: 0}
      },
    },
    cd: { type: Number, default: 0 },
    duration: { type: Number, default: 0 },
    range: { type: Number, default: 0 },
    isLegendary: { type: Boolean, default: false },
  });

export const ItemModel = mongoose.model('items', itemSchema);