import mongoose from 'mongoose';

const itemSchema = mongoose.Schema({
    name: { type: String, required: true, unique: true },
    description: { type: String },
    thumbnail: { type: String },
    kind: { type: String, default: 'verkaufbar' },
    rang: { type: Number, default: 0 },
    weight: { type: Number, default: 1 },
    stacksize: { type: Number, default: 1 },
    sell: { type: Number, default: 0 },
    price: { type: Number, default: 0 },
    rare: { type: Number, default: 3 },
    slots: { type: Number, default: 0 },
    type: { type: String},
    level: { type: Number, default: 1 },
    pang: { type: Number, default: 0 },
    mang: { type: Number, default: 0 },
    pdeff: { type: Number, default: 0 },
    crit: { type: Number, default: 0 },
    block: { type: Number, default: 0 },
    speed: { type: Number, default: 0 },
    health: { type: Number, default: 0 },
    mana: { type: Number, default: 0 },
    agility: { type: Number, default: 0 },
    ambush: { type: Number, default: 0 },
    dexerity: { type: Number, default: 0 },
    faith: { type: Number, default: 0 },
    int: { type: Number, default: 0 },
    strength: { type: Number, default: 0 },
    victim: { type: Number, default: 0 },
    vita: { type: Number, default: 0 },
    wisdom: { type: Number, default: 0 },
    luck: { type: Number, default: 0 },
    cd: { type: Number, default: 0 },
    duration: { type: Number, default: 0 },

    weapon: {
      w_type: { type: String },
      w_slots: { type: Number, default: 0 },
      w_level: { type: Number, default: 0 },
      w_plus: { type: Number, default: 0 },
      a_pang: { type: Number, default: 0 },
      a_mang: { type: Number, default: 0 },
      a_pdeff: { type: Number, default: 0 },
      a_crit: { type: Number, default: 0 },
      a_block: { type: Number, default: 0 },
      a_speed: { type: Number, default: 0 },
      a_agi: { type: Number, default: 0 },
      a_amb: { type: Number, default: 0 },
      a_dex: { type: Number, default: 0 },
      a_faith: { type: Number, default: 0 },
      a_int: { type: Number, default: 0 },
      a_str: { type: Number, default: 0 },
      a_vic: { type: Number, default: 0 },
      a_vita: { type: Number, default: 0 },
      a_wis: { type: Number, default: 0 },
      w_upgrades: { type: [String], maxlength: 5 },
    },
    
  });

export const ItemModel = mongoose.model('items', itemSchema);